### ISSUE TITLE
Compatibility for additional query points

### ISSUE THREAD

**Issue by hamdjalil** [google-deepmind/tapnet#122]
Is there any way to incorporate query points from more than one frame in TAPIR?

so for instance, currently I believe we have a 1-shot approach where we select query points from one chosen frame.
Is there a way I can incorporate query points from multiple chosen frames for the same video? I'm trying to assess how much this would affect the performance.

One way would be to run inference separately for separate (frame,query_points) and find a way to merge the results for a best-case scenario, but this would consume a lot of resources.

I attempted to alter the query_points input for TAPIR model inference as a batch input with multiple frames and corresponding query points but I get an error, so just wondering if there is, if any, a way to do that.

Thanks!

**Comment by cdoersch** [comment]
The query points have the format [t,y,x] where t is the desired frame.  You should be able to query on arbitrary frames out of the box.

What error are you getting?

**Comment by hamdjalil** [comment]
how can i use a batch query for a single inference? 
for instance, [s,t,y,x] where s is the number of frames

**Comment by jeffyu880** [comment]
Hi @hamdjalil, were you able to implement the addition of multiple query points? I'm having issues with the update_query_features function where I pass in multiple points and there's a dimension error.

**Comment by hamdjalil** [comment]
I was able to do that, but I found that the model is just overlaying multiple videos in the output.

so if i sent a list of query points q1,q2,q3 the output would inference the entire video for q1 producing video with keypoints: vs1, and then followed by vs2 for q2 and vs3 for q3 and overlay the results in the same video, which was causing a clutter so it wasn't very helpful for me.

I think there was a specific input shape which allowed me to run it this way and bypass the dimension error, I might not have access to the script now but if you're still interested in running it you could share the error and I can see if I remember the resolution.

**Comment by jeffyu880** [comment]
Hey thanks for the response, I am running the live_demo.py script because I want to use the webcam,

these are the query_points. 
[[          0         312          80]
 [          0         335          82]
 [          0         315         121]
 [          0         331         115]
 [          0         283         161]]

the error is ValueError: Incompatible shapes for broadcasting: (1, 5, 256) and requested shape (1, 1, 256) when I call the update_query_features function

**Comment by cdoersch** [comment]
What are you passing as idx_to_update?  If you're updating 5 points at a time, you need to pass 5 indices.  

Can you post the full stack trace?

**Comment by jeffyu880** [comment]
Traceback (most recent call last):
  File "C:\EPFL\Fall_2024\WasteFlow\tapnet\tapnet\live_demo_video.py", line 315, in <module>
    query_features, causal_state = tapir.update_query_features(
  File "C:\EPFL\Fall_2024\WasteFlow\tapnet\tapnet\models\tapir_model.py", line 1237, in run
    res = hk_fn.apply(
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\haiku\_src\transform.py", line 456, in apply_fn
    out = f(*args, **kwargs)
  File "C:\EPFL\Fall_2024\WasteFlow\tapnet\tapnet\models\tapir_model.py", line 1232, in tapir_call      
    return fn(*args, **kwargs)
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\haiku\_src\module.py", line 464, in wrapped
    out = f(*args, **kwargs)
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\haiku\_src\module.py", line 305, in run_interceptors
    return bound_method(*args, **kwargs)
  File "C:\EPFL\Fall_2024\WasteFlow\tapnet\tapnet\models\tapir_model.py", line 1168, in update_query_features
    lowres=jax.tree_util.tree_map(
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\jax\_src\tree_util.py", line 343, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\jax\_src\tree_util.py", line 343, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "C:\EPFL\Fall_2024\WasteFlow\tapnet\tapnet\models\tapir_model.py", line 1165, in apply_update_idx
    return s1.at[:, idx_to_update].set(s2)
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\jax\_src\numpy\array_methods.py", line 493, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\jax\_src\ops\scatter.py", line 80, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\jax\_src\ops\scatter.py", line 115, in _scatter_impl
    y = jnp.broadcast_to(y, tuple(indexer.slice_shape))
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\jax\_src\numpy\lax_numpy.py", line 2087, in broadcast_to
    return util._broadcast_to(array, shape)
  File "C:\Users\jeffr\anaconda3\envs\tapir_yolo\lib\site-packages\jax\_src\numpy\util.py", line 430, in _broadcast_to
    raise ValueError(msg.format(arr_shape, shape))
ValueError: Incompatible shapes for broadcasting: (1, 5, 256) and requested shape (1, 1, 256)

in my code: idx_to_update=np.array([next_query_idx]). I suppose I pass in an array with 5 indices?

**Comment by cdoersch** [comment]
> idx_to_update=np.array([next_query_idx]). I suppose I pass in an array with 5 indices?

Yes

**Comment by jeffyu880** [comment]
Thanks! Is there anyway to remove query points?

**Comment by cdoersch** [comment]
You probably don't want to do this because it will result in a recompile, which can take over a minute.  However, for both causal_state and query_features, the relevant information for each point is stacked along the first axis.  It should be straightforward to change this function: https://github.com/google-deepmind/tapnet/blob/main/tapnet/models/tapir_model.py#L1157 so that it deletes a given index rather than adds it.  tree_util.tree_map can be called with a single arg.
