### ISSUE TITLE
Assertion Error in rc5 While Generating ADT Annotations

### ISSUE THREAD

**Issue by yuantianyuan01** [google-deepmind/tapnet#129]
Hi,

Thank you again for including extrinsics in version rc5! However, I encountered an assertion error when using the new rc5 .npz files to generate ADT annotations. Specifically, I ran the following command: 
`python3 -m tapnet.tapvid3d.annotation_generation.generate_adt --adt_base_path /mnt/datasets/tapvid-3d/Aria_Digital_Twin/ --output_dir /mnt/datasets/tapvid-3d/adt/ --debug` 
And got the following error:
```
Traceback (most recent call last):
  File "/home/yuantianyuan/miniconda3/envs/tapnet/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yuantianyuan/miniconda3/envs/tapnet/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/yuantianyuan/code/tapnet/tapnet/tapvid3d/annotation_generation/generate_adt.py", line 114, in <module>
    app.run(main)
  File "/home/yuantianyuan/miniconda3/envs/tapnet/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/yuantianyuan/miniconda3/envs/tapnet/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/yuantianyuan/code/tapnet/tapnet/tapvid3d/annotation_generation/generate_adt.py", line 110, in main
    generate_adt_npz(_ADT_BASE_PATH.value, tmp_adt_dir, _OUTPUT_DIR.value)
  File "/home/yuantianyuan/code/tapnet/tapnet/tapvid3d/annotation_generation/generate_adt.py", line 90, in generate_adt_npz
    adt_utils.process_vid(
  File "/home/yuantianyuan/code/tapnet/tapnet/tapvid3d/annotation_generation/adt_utils.py", line 177, in process_vid
    assert np.allclose(video_means, in_npz["video_means"], atol=1e-3)
AssertionError
```
When I switched back to rc4, the error didn’t occur. After checking I found the only difference between the rc4 and rc5 .npz files is the key `video_mean` (apart from the newly added `extrinsics_w2c`). I checked sequences like `Apartment_release_meal_seq136_8` and `Lite_release_recognition_GreenDecorationTall_seq031_6`, and the `video_means` values were all different between rc4 and rc5. 

This leads me to believe there might be an issue with how the video_means values were generated in the rc5 .npz files. Could you confirm if this is expected or if there might be an error in the rc5 data generation?

Thanks for your help!

**Comment by ignacio-rocco** [comment]
Hi Yuan Tian,

Thanks for reporting this issue. I've updated the 'video_means' field in the rc5 npz files. Let me know if this solves the issue.
