### ISSUE TITLE
Issue when evaluating TAP-IR on DAVIS

### ISSUE THREAD

**Issue by AssafSinger94** [google-deepmind/tapnet#61]
When trying to evaluate TAP-IR locally on a GPU on DAVIS, as follows:
```
python3 ./tapnet/experiment.py \
  --config=./tapnet/configs/tapir_config.py \
  --jaxline_mode=eval_davis_points \
  --config.checkpoint_dir=./tapnet/checkpoints_tapir/ \
  --config.experiment_kwargs.config.davis_points_path=/path/to/tapvid_davis.pkl
```
  (I downloaded `checkpoints/tapir_checkpoint_panning.npy` and moved it to `checkpoints_tapir/checkpoint.npy`)
  I am encountering the following error:
  
```
  Traceback (most recent call last):
  File "/home/projects/talide/assafsin/projects/tapir/./tapnet/experiment.py", line 431, in <module>
    app.run(main)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/projects/talide/assafsin/projects/tapir/./tapnet/experiment.py", line 424, in main
    platform.main(
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/utils.py", line 522, in inner_wrapper
    return f(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/platform.py", line 137, in main
    train.evaluate(experiment_class, config, checkpointer, writer,
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/utils.py", line 658, in inner_wrapper
    return fn(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/train.py", line 240, in evaluate
    scalar_values = utils.evaluate_should_return_dict(experiment.evaluate)(
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/utils.py", line 559, in evaluate_with_warning
    evaluate_out = f(*args, **kwargs)
  File "/home/projects/talide/assafsin/projects/tapir/./tapnet/experiment.py", line 405, in evaluate
    eval_scalars = point_prediction_task.evaluate(
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/supervised_point_prediction.py", line 387, in evaluate
    self._eval_epoch(
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/supervised_point_prediction.py", line 907, in _eval_epoch
    scalars, viz = eval_batch_fn(params, state, inputs, rng)
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/supervised_point_prediction.py", line 621, in _eval_batch
    outputs, loss_scalars = self._infer_batch(
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/supervised_point_prediction.py", line 447, in _infer_batch
    output, _ = functools.partial(wrapped_forward_fn, input_key=input_key)(
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/transform.py", line 457, in apply_fn
    out = f(*args, **kwargs)
  File "/home/projects/talide/assafsin/projects/tapir/./tapnet/experiment.py", line 125, in forward
    return self.point_prediction.forward_fn(
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/supervised_point_prediction.py", line 153, in forward_fn
    return shared_modules[self.model_key](
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 465, in wrapped
    out = f(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 306, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/tapir_model.py", line 1026, in __call__
    trajectories = self.estimate_trajectories(
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 465, in wrapped
    out = f(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 306, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/tapir_model.py", line 918, in estimate_trajectories
    refined = self.refine_pips(
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 465, in wrapped
    out = f(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 306, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/tapir_model.py", line 544, in refine_pips
    res, new_causal_context = self.pips_mixer(
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 465, in wrapped
    out = f(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 306, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/tapir_model.py", line 144, in __call__
    x = hk.Linear(self.hidden_dim)(x)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 465, in wrapped
    out = f(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/module.py", line 306, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/basic.py", line 178, in __call__
    w = hk.get_parameter("w", [input_size, output_size], dtype, init=w_init)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/base.py", line 602, in wrapped
    return wrapped._current(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/haiku/_src/base.py", line 707, in get_parameter
    raise ValueError(
ValueError: 'tapir/~/pips_mlp_mixer/linear/w' with retrieved shape (486, 512) does not match shape=[535, 512] dtype=dtype('float32')
```
`x.shape = (16, 90, 535)` and the components that comprise mlp_input are of the 
`pos_guess_input.shape=(1, 16, 90, 2), occ_guess_input.shape=(1, 16, 90, 1),  expd_guess_input.shape=(1, 16, 90, 1), mlp_input_features.shape=(1, 16, 90, 384),  corrs_chunked.shape=(1, 16, 90, 147),`

I didn't changed anything in the dimensions of the videos of DAVIS or in the tapir config.
I would really appreciate your assistance, thanks!

**Comment by yangyi02** [comment]
Apologize for the trouble.

The tapir_checkpoint_panning model slightly differs from our default tapir config where the pyramid level should be 0. Otherwise there will be shape mismatch.

See the colab notebook as an example: `model = tapir_model.TAPIR(bilinear_interp_with_depthwise_conv=False, pyramid_level=0)`

So for a temporary fix, please add `pyramid_level=0` to the `configs/tapir_config.py`, change below

```
tapir_model_kwargs=dict(
                    bilinear_interp_with_depthwise_conv=True,
                    use_causal_conv=False,
                    initial_resolution=(256, 256),
                ),
```

to 

```
tapir_model_kwargs=dict(
                    bilinear_interp_with_depthwise_conv=True,
                    use_causal_conv=False,
                    initial_resolution=(256, 256),
                    pyramid_level=0,
                ),
```

**Comment by AssafSinger94** [comment]
It worked! thank you very much.
