### ISSUE TITLE
"OSError: [Errno 14] Bad address" : when trying to evaluate TAP-Net & TAP-IR on Kinetics

### ISSUE THREAD

**Issue by AssafSinger94** [google-deepmind/tapnet#64]
Hi,
When trying to evaluate the model on TAP-Vid Kinetics, I am encountering the following error (described in comments below).
The error seem to occur during yielding of an example using `create_kinetics_dataset`, after the evaluation was done for all the videos in the first pickle file `0000_of_0010.pkl`.
I was able to evaluate the models on TAP-Vid DAVIS properly.
I am running the following code on an NVIDIA-A100 GPU (the GPU with the most memory that I have access to).
```
python ./tapnet/experiment.py \
--config=./tapnet/configs/tapnet_config.py \
--jaxline_mode=eval_kinetics_points \
--config.checkpoint_dir=./tapnet/checkpoints_tapnet/ \
--config.experiment_kwargs.config.kinetics_points_path=<path_to_tapvid_kinetics_pkl_files_dir>
```
I manually added `kinetics_points_path` parameter to `tapnet_config.py` & `tapir_config.py` which was missing.

Could you please assist me in the matter?
Assaf

**Comment by AssafSinger94** [comment]
```
I1020 17:06:48.536417 47193737840832 supervised_point_prediction.py:972] eval batch: 115
I1020 17:06:48.542387 47193737840832 supervised_point_prediction.py:983] {'average_jaccard': Array(0.22719689, dtype=float32), 'average_pts_within_thresh': Array(0.3231358, dtype=float32), 'jaccard_1': Array(0.05189561, dtype=float32), 'jaccard_16': Array(0.40190077, dtype=float32), 'jaccard_2': Array(0.13956638, dtype=float32), 'jaccard_4': Array(0.23128213, dtype=float32), 'jaccard_8': Array(0.3113395, dtype=float32), 'loss_occ': Array(0.5958628, dtype=float32), 'occlusion_accuracy': Array(0.7661699, dtype=float32), 'position_loss': Array(66.85089, dtype=float32), 'pts_within_1': Array(0.09040983, dtype=float32), 'pts_within_16': Array(0.5609231, dtype=float32), 'pts_within_2': Array(0.21031761, dtype=float32), 'pts_within_4': Array(0.32336652, dtype=float32), 'pts_within_8': Array(0.43066198, dtype=float32)}
ckpt_series latest
Restoring checkpoint from ./tapnet/checkpoints_tapnet/checkpoint.npy
Traceback (most recent call last):
  File "/home/projects/talide/assafsin/projects/tapir/./tapnet/experiment.py", line 431, in <module>
    app.run(main)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/projects/talide/assafsin/projects/tapir/./tapnet/experiment.py", line 424, in main
    platform.main(
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/utils.py", line 522, in inner_wrapper
    return f(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/platform.py", line 137, in main
    train.evaluate(experiment_class, config, checkpointer, writer,
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/utils.py", line 658, in inner_wrapper
    return fn(*args, **kwargs)
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/train.py", line 240, in evaluate
    scalar_values = utils.evaluate_should_return_dict(experiment.evaluate)(
  File "/home/projects/talide/assafsin/micromamba/envs/amit3/lib/python3.10/site-packages/jaxline/utils.py", line 559, in evaluate_with_warning
    evaluate_out = f(*args, **kwargs)
  File "/home/projects/talide/assafsin/projects/tapir/./tapnet/experiment.py", line 405, in evaluate
    eval_scalars = point_prediction_task.evaluate(
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/supervised_point_prediction.py", line 387, in evaluate
    scalars = jax.device_get(
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/supervised_point_prediction.py", line 904, in _eval_epoch
    )
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/supervised_point_prediction.py", line 734, in _build_eval_input
    elif 'eval_kinetics_points' in mode:
  File "/home/projects/talide/assafsin/projects/tapir/tapnet/evaluation_datasets.py", line 560, in create_kinetics_dataset
    data = pickle.load(f)
OSError: [Errno 14] Bad address
```

**Comment by cdoersch** [comment]
Not aware of others reproducing this issue, so I'm closing.  Feel free to reopen if others are having the same issue.
