### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 1; dimension is 256 but corresponding boolean dimension is 990

### ISSUE THREAD

**Issue by nutsintheshell** [google-deepmind/tapnet#89]
When I run cluster colab demo without any changing, the error occurred.

Traceback (most recent call last):
  File "/tapnet/example/cluster.py", line 30, in <module>
    clustered = tapir_clustering.compute_clusters(
  File "/tapnet/tapir_clustering.py", line 570, in compute_clusters
    query_features = jax.tree_map(
  File "/root/miniconda3/envs/robosuite/lib/python3.10/site-packages/jax/_src/tree_util.py", line 312, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/root/miniconda3/envs/robosuite/lib/python3.10/site-packages/jax/_src/tree_util.py", line 312, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/tapnet/tapir_clustering.py", line 571, in <lambda>
    lambda x: x[:, enough_visible] if len(x.shape) > 1 else x,
IndexError: boolean index did not match indexed array along dimension 1; dimension is 256 but corresponding boolean dimension is 1290

Could someone tell me how to solve it?

**Comment by cdoersch** [comment]
I think I see what the problem is here.  The format of QueryFeatures has changed: it now keeps track of the input shape as a zero-sized array rather than as a 2-tuple, which was done to make jit work as expected.  Unfortunately this particular line hasn't been updated: we need index into the relevant fields of QueryFeatures, but not the shape.  The code at tapir_clustering.py line 571 uses the test `len(x.shape) > 1` to make sure the shape field doesn't get indexed, but this test no longer works after the update, so the code tries to index the shape and it crashes.

The fix should be straightforward; changing `len(x.shape) > 1` to `x.shape[-1] > 0` should make this line succeed. However, I don't immediately have time to fully test whether this makes the code work; please let me know if there's other errors after this line is fixed and I'll try my best to find fixes.

**Comment by cdoersch** [comment]
This should be fixed with today's update; I've tested that the tapir_clustering.py runs at head now.  Please re-open if you have other issues.
